version: '3'

services:
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        networks:
            - prestashop
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: prestashop
    apache:
        image: prestashop/prestashop:1.6-7.1-apache
        networks:
            - prestashop
        depends_on:
            - mysql
        links:
            - mysql
        environment:
            PS_INSTALL_AUTO: 1
            DB_PASSWD: password
            DB_NAME: prestashop
            DB_SERVER: mysql
            PS_DOMAIN: localhost
            PS_FOLDER_INSTALL: install-dev
            PS_FOLDER_ADMIN: admin-dev
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html/modules/dropday

networks:
    prestashop: