name: Attach ZIP to Release

on:
  push:
    branches:
      - master

jobs:
  attach-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Module Version
        id: get_version
        run: |
          MODULE_FILE="dropday.php"
          if [ ! -f "$MODULE_FILE" ]; then
            echo "dropday.php not found. Exiting."
            exit 1
          fi
          VERSION=$(sed -nE 's/^\s*\$this->version\s*=\s*["'\'']([^"'\'' ]+)["'\''];/\1/p' "$MODULE_FILE")
          if [ -z "$VERSION" ]; then
            echo "Version not found in $MODULE_FILE. Exiting."
            exit 1
          fi
          echo "MODULE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION"  # Display for debugging

      - name: Create ZIP Archive
        if: env.RELEASE_EXISTS == 'false'
        run: |
          # Maak een tijdelijke map voor de module
          mkdir -p temp/dropday
          
          # Kopieer alle nodige bestanden naar de dropday map
          rsync -av --exclude=".git" --exclude=".github" --exclude="temp" --exclude=".env" --exclude="docker-compose.yml" ./ temp/dropday/
          
          # Ga naar de temp directory en maak de ZIP
          cd temp
          zip -r "../dropday.zip" dropday
          cd ..
          
          # Opruimen
          rm -rf temp

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${MODULE_VERSION}" "dropday.zip" \
            --title "${MODULE_VERSION}" \
            --notes "Release version ${MODULE_VERSION}." \
            --draft

      - name: Upload Release Asset via GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${MODULE_VERSION}" "dropday.zip" --clobber --repo "${{ github.repository }}"
