name: Attach ZIP to Release

on:
  release:
    types: [published]

jobs:
  attach-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP Archive
        run: zip -r release.zip . -x "*.git*" -x ".env"

      - name: Upload Release Asset via GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.event.release.tag_name }}" release.zip \
            --clobber \
            --repo "${{ github.repository }}" \
            --name "dropday_${{ github.event.release.tag_name }}.zip"
